server {
  listen 80;
  root /usr/share/nginx/html;
  gzip on;
  gzip_types text/css application/javascript application/json image/svg+xml;

  # arquivos com hash no nome nunca mudam
  location /_next/static/ { expires 1y; add_header Cache-Control "public, immutable"; }
  location /portfolio/vertice/ { expires 30d; }

  location / { try_files $uri $uri/ $uri.html =404; }
  error_page 404 /404.html;
}
